//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KyTucXa
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyDichVu
    {
        public string Id { get; set; }
        public string MaDV { get; set; }
        public string MaSV { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
