//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KyTucXa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public Nullable<decimal> TienDien { get; set; }
        public Nullable<decimal> TienNuoc { get; set; }
        public Nullable<decimal> TienPhong { get; set; }
        public Nullable<decimal> TienDV { get; set; }
        public string MaSV { get; set; }
        public Nullable<System.DateTime> NgayXuatHoaDon { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
